"""Board & Committee Governance API — committees, meetings (agenda/minutes/attendance),
a decision / action tracker, and board packs.

Maintain the committee register with charters and cadence, minute each sitting through
its lifecycle, and log decisions / actions / resolutions that roll up into an
enterprise-wide action tracker with an overdue view.

Board packs (phase 3, ``services/board_pack.py``): ``POST /board-packs`` builds the
committee's pack for a period (default the fiscal quarter to date) from the dashboard's
own figures plus the period's movement, renders it as PDF and XLSX, files both (on the
meeting when one is given) and keeps a ``BoardPack`` row; ``GET /board-packs`` lists
them and ``/board-packs/{id}/pdf|xlsx`` download the files. A committee with
``board_pack_days_before`` set gets its pack generated by the scheduler that many days
before each scheduled meeting.
"""
from __future__ import annotations

import uuid
from datetime import date
from typing import Annotated

from urllib.parse import quote

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse
from sqlalchemy import Select, func, select

from app.core.deps import CurrentUser, DbSession, require
from app.core.listing import ListParams, apply_sort
from app.models.collab import StoredFile
from app.models.governance import (
    BoardPack,
    Committee,
    CommitteeStatus,
    CommitteeType,
    DecisionStatus,
    Meeting,
    MeetingDecision,
    MeetingStatus,
)
from app.schemas.common import Page
from app.schemas.governance import (
    BoardPackCreate,
    BoardPackFile,
    BoardPackRead,
    BoardPackSection,
    CommitteeCreate,
    CommitteeRead,
    CommitteeUpdate,
    DecisionCreate,
    DecisionRead,
    DecisionTrackerRow,
    DecisionUpdate,
    GovernanceSummary,
    MeetingCreate,
    MeetingRead,
    MeetingUpdate,
)
from app.services.refs import next_reference
from app.services import audit as audit_log
from app.services import board_pack, master_data, storage

router = APIRouter(tags=["governance"])

_READ = Depends(require("governance:read"))
_WRITE = Depends(require("governance:write"))


async def _next_ref(db, model, prefix: str) -> str:
    return await next_reference(db, model, prefix)


_COMMITTEE_SORTABLE = {
    "name": Committee.name,
    "reference": Committee.reference,
    "committee_type": Committee.committee_type,
    "chairperson": Committee.chairperson,
    "status": Committee.status,
    "created_at": Committee.created_at,
}
_DECISION_SORTABLE = {
    "reference": MeetingDecision.reference,
    "description": MeetingDecision.description,
    "decision_type": MeetingDecision.decision_type,
    "owner": MeetingDecision.owner,
    "status": MeetingDecision.status,
    "due_date": MeetingDecision.due_date,
    "committee": Committee.name,
    "meeting": Meeting.title,
    "created_at": MeetingDecision.created_at,
}


# ============================================================== committees ===
async def _load_committee(db, cid: uuid.UUID) -> Committee:
    obj = await db.scalar(
        select(Committee).where(Committee.id == cid, Committee.deleted.is_(False)).execution_options(populate_existing=True)
    )
    if obj is None:
        raise HTTPException(status_code=404, detail="Committee not found")
    return obj


@router.get("/governance", response_model=Page[CommitteeRead], dependencies=[_READ])
async def list_committees(
    db: DbSession,
    search: str | None = None,
    committee_type: CommitteeType | None = None,
    status_filter: Annotated[CommitteeStatus | None, Query(alias="status")] = None,
    sort_by: Annotated[str | None, Query()] = None,
    sort_dir: Annotated[str, Query(pattern="^(asc|desc)$")] = "asc",
    limit: Annotated[int, Query(ge=1, le=200)] = 100,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> Page[CommitteeRead]:
    stmt: Select = select(Committee).where(Committee.deleted.is_(False))
    if committee_type is not None:
        stmt = stmt.where(Committee.committee_type == committee_type)
    if status_filter is not None:
        stmt = stmt.where(Committee.status == status_filter)
    if search:
        like = f"%{search}%"
        stmt = stmt.where(
            Committee.name.ilike(like)
            | Committee.chairperson.ilike(like)
            | Committee.reference.ilike(like)
        )
    if sort_by:
        params = ListParams(limit=limit, offset=offset, sort_by=sort_by, sort_dir=sort_dir, q=search)
        stmt = apply_sort(stmt, params, _COMMITTEE_SORTABLE, default=Committee.name)
    else:
        stmt = stmt.order_by(Committee.name)
    total = await db.scalar(select(func.count()).select_from(stmt.subquery())) or 0
    rows = (await db.scalars(stmt.limit(limit).offset(offset))).all()
    return Page(items=[CommitteeRead.model_validate(r) for r in rows], total=total, limit=limit, offset=offset)


@router.post("/governance", response_model=CommitteeRead, status_code=201, dependencies=[_WRITE])
async def create_committee(body: CommitteeCreate, db: DbSession, user: CurrentUser) -> CommitteeRead:
    obj = Committee(tenant_id=user.tenant_id, **body.model_dump())
    obj.reference = await _next_ref(db, Committee, "CMT")
    db.add(obj)
    await db.flush()
    await audit_log.record(db, actor=user, action="create", entity_type="committee",
                           entity_id=obj.id, summary=f"Constituted committee {obj.reference}: {obj.name}")
    return CommitteeRead.model_validate(await _load_committee(db, obj.id))


@router.get("/governance/{cid}", response_model=CommitteeRead, dependencies=[_READ])
async def get_committee(cid: uuid.UUID, db: DbSession) -> CommitteeRead:
    return CommitteeRead.model_validate(await _load_committee(db, cid))


def _plain(value):
    return getattr(value, "value", value)


#: Fields that may be cleared (sent as null); every other null in a PATCH is ignored.
_NULLABLE_COMMITTEE_FIELDS = frozenset({"board_pack_days_before"})


@router.patch("/governance/{cid}", response_model=CommitteeRead, dependencies=[_WRITE])
async def update_committee(cid: uuid.UUID, body: CommitteeUpdate, db: DbSession, user: CurrentUser) -> CommitteeRead:
    obj = await _load_committee(db, cid)
    changes: dict = {}
    for k, v in body.model_dump(exclude_unset=True).items():
        if v is None and k not in _NULLABLE_COMMITTEE_FIELDS:
            continue
        before = getattr(obj, k)
        if before != v:
            changes[k] = {"from": _plain(before), "to": _plain(v)}
        setattr(obj, k, v)
    await db.flush()
    if changes:
        auto = changes.get("board_pack_days_before")
        note = ""
        if auto is not None:
            note = (f"; board pack generated {auto['to']} day(s) before each meeting" if auto["to"]
                    else "; board pack no longer generated automatically")
        await audit_log.record(db, actor=user, action="update", entity_type="committee", entity_id=obj.id,
                               summary=f"Updated committee {obj.reference}: {', '.join(changes)}{note}"[:500],
                               changes=changes)
    return CommitteeRead.model_validate(await _load_committee(db, cid))


@router.delete("/governance/{cid}", status_code=204, dependencies=[_WRITE])
async def delete_committee(cid: uuid.UUID, db: DbSession, user: CurrentUser) -> None:
    obj = await _load_committee(db, cid)
    obj.deleted = True
    obj.deleted_date = date.today()
    await db.flush()
    await audit_log.record(db, actor=user, action="delete", entity_type="committee", entity_id=obj.id,
                           summary=f"Archived committee {obj.reference}: {obj.name}")


# ================================================================= meetings ===
async def _load_meeting(db, mid: uuid.UUID) -> Meeting:
    # Meetings have no archive flag of their own (they are deleted outright); a meeting
    # of an archived committee is gone with it. (This used to filter on a
    # ``Meeting.deleted`` column that does not exist, so every call failed.)
    obj = await db.scalar(
        select(Meeting)
        .join(Committee, Committee.id == Meeting.committee_id)
        .where(Meeting.id == mid, Committee.deleted.is_(False))
        .execution_options(populate_existing=True)
    )
    if obj is None:
        raise HTTPException(status_code=404, detail="Meeting not found")
    return obj


@router.post("/governance/{cid}/meetings", response_model=CommitteeRead, status_code=201, dependencies=[_WRITE])
async def add_meeting(cid: uuid.UUID, body: MeetingCreate, db: DbSession, user: CurrentUser) -> CommitteeRead:
    await _load_committee(db, cid)
    meeting = Meeting(tenant_id=user.tenant_id, committee_id=cid, **body.model_dump())
    meeting.reference = await _next_ref(db, Meeting, "MTG")
    db.add(meeting)
    await db.flush()
    await audit_log.record(db, actor=user, action="create", entity_type="committee_meeting",
                           entity_id=meeting.id, summary=f"Scheduled meeting {meeting.reference}: {meeting.title}")
    return CommitteeRead.model_validate(await _load_committee(db, cid))


@router.get("/governance-meetings/{mid}", response_model=MeetingRead, dependencies=[_READ])
async def get_meeting(mid: uuid.UUID, db: DbSession) -> MeetingRead:
    return MeetingRead.model_validate(await _load_meeting(db, mid))


@router.patch("/governance-meetings/{mid}", response_model=MeetingRead, dependencies=[_WRITE])
async def update_meeting(mid: uuid.UUID, body: MeetingUpdate, db: DbSession, user: CurrentUser) -> MeetingRead:
    obj = await _load_meeting(db, mid)
    changes: dict = {}
    for k, v in body.model_dump(exclude_unset=True).items():
        if v is None and k != "meeting_date":
            continue
        before = getattr(obj, k)
        if before != v:
            changes[k] = {"from": str(_plain(before)) if k in ("meeting_date",) else _plain(before),
                          "to": str(_plain(v)) if k in ("meeting_date",) else _plain(v)}
        setattr(obj, k, v)
    await db.flush()
    if changes:
        await audit_log.record(db, actor=user, action="update", entity_type="committee_meeting", entity_id=obj.id,
                               summary=f"Updated meeting {obj.reference}: {', '.join(changes)}"[:500],
                               changes={k: v for k, v in changes.items() if k not in ("agenda", "minutes", "attendees")})
    return MeetingRead.model_validate(await _load_meeting(db, mid))


@router.delete("/governance-meetings/{mid}", status_code=204, dependencies=[_WRITE])
async def delete_meeting(mid: uuid.UUID, db: DbSession, user: CurrentUser) -> None:
    obj = await db.scalar(select(Meeting).where(Meeting.id == mid))
    if obj is None:
        raise HTTPException(status_code=404, detail="Record not found")
    label = f"{obj.reference}: {obj.title}"
    await db.delete(obj)
    await db.flush()
    await audit_log.record(db, actor=user, action="delete", entity_type="committee_meeting", entity_id=mid,
                           summary=f"Deleted meeting {label}"[:500])


# ---------------------------------------------------- decisions (per meeting) ---
def _stamp_decision(obj: MeetingDecision, data: dict) -> None:
    """Auto-manage completed_date as a decision moves in and out of 'done'."""
    if data.get("status") == DecisionStatus.done and not obj.completed_date and "completed_date" not in data:
        obj.completed_date = date.today()
    if data.get("status") in (DecisionStatus.open, DecisionStatus.in_progress, DecisionStatus.deferred):
        obj.completed_date = data.get("completed_date")


@router.post("/governance-meetings/{mid}/decisions", response_model=MeetingRead, status_code=201, dependencies=[_WRITE])
async def add_decision(mid: uuid.UUID, body: DecisionCreate, db: DbSession, user: CurrentUser) -> MeetingRead:
    await _load_meeting(db, mid)
    decision = MeetingDecision(tenant_id=user.tenant_id, meeting_id=mid, **body.model_dump())
    decision.reference = await _next_ref(db, MeetingDecision, "DEC")
    if decision.status == DecisionStatus.done and decision.completed_date is None:
        decision.completed_date = date.today()
    db.add(decision)
    await db.flush()
    await audit_log.record(db, actor=user, action="create", entity_type="committee_meeting", entity_id=mid,
                           summary=f"Logged {decision.decision_type.value} {decision.reference}: {decision.description}"[:500])
    return MeetingRead.model_validate(await _load_meeting(db, mid))


async def _load_decision(db, did: uuid.UUID) -> MeetingDecision:
    obj = await db.scalar(select(MeetingDecision).where(MeetingDecision.id == did))
    if obj is None:
        raise HTTPException(status_code=404, detail="Decision not found")
    return obj


@router.patch("/meeting-decisions/{did}", response_model=DecisionRead, dependencies=[_WRITE])
async def update_decision(did: uuid.UUID, body: DecisionUpdate, db: DbSession, user: CurrentUser) -> DecisionRead:
    obj = await _load_decision(db, did)
    data = body.model_dump(exclude_unset=True)
    _stamp_decision(obj, data)
    changes = {k: {"from": str(_plain(getattr(obj, k))), "to": str(_plain(v))}
               for k, v in data.items() if getattr(obj, k) != v}
    for k, v in data.items():
        setattr(obj, k, v)
    await db.flush()
    if changes:
        await audit_log.record(db, actor=user, action="update", entity_type="committee_meeting",
                               entity_id=obj.meeting_id,
                               summary=f"Updated {obj.decision_type.value} {obj.reference}: {', '.join(changes)}"[:500],
                               changes=changes)
    return DecisionRead.model_validate(obj)


@router.delete("/meeting-decisions/{did}", status_code=204, dependencies=[_WRITE])
async def delete_decision(did: uuid.UUID, db: DbSession, user: CurrentUser) -> None:
    obj = await db.scalar(select(MeetingDecision).where(MeetingDecision.id == did))
    if obj is None:
        raise HTTPException(status_code=404, detail="Record not found")
    meeting_id, label = obj.meeting_id, f"{obj.reference}: {obj.description}"
    await db.delete(obj)
    await db.flush()
    await audit_log.record(db, actor=user, action="delete", entity_type="committee_meeting", entity_id=meeting_id,
                           summary=f"Removed decision/action {label}"[:500])


@router.get("/meeting-decisions", response_model=Page[DecisionTrackerRow], dependencies=[_READ],
            summary="Enterprise decision / action tracker across all committees")
async def list_decisions(
    db: DbSession,
    search: str | None = None,
    status_filter: Annotated[DecisionStatus | None, Query(alias="status")] = None,
    overdue: bool = False,
    sort_by: Annotated[str | None, Query()] = None,
    sort_dir: Annotated[str, Query(pattern="^(asc|desc)$")] = "asc",
    limit: Annotated[int, Query(ge=1, le=200)] = 50,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> Page[DecisionTrackerRow]:
    stmt = (
        select(MeetingDecision, Meeting, Committee)
        .join(Meeting, MeetingDecision.meeting_id == Meeting.id)
        .join(Committee, Meeting.committee_id == Committee.id)
        .where(Committee.deleted.is_(False))
    )
    if status_filter is not None:
        stmt = stmt.where(MeetingDecision.status == status_filter)
    if overdue:
        # `is_overdue` mirrored as SQL so the filter works with server-side pagination.
        stmt = stmt.where(
            MeetingDecision.status.in_([DecisionStatus.open, DecisionStatus.in_progress]),
            MeetingDecision.due_date.is_not(None),
            MeetingDecision.due_date < date.today(),
        )
    if search:
        like = f"%{search}%"
        stmt = stmt.where(
            MeetingDecision.description.ilike(like)
            | MeetingDecision.owner.ilike(like)
            | MeetingDecision.reference.ilike(like)
            | Committee.name.ilike(like)
            | Meeting.title.ilike(like)
        )
    total = await db.scalar(
        select(func.count()).select_from(
            stmt.with_only_columns(MeetingDecision.id).order_by(None).subquery()
        )
    ) or 0
    if sort_by:
        params = ListParams(limit=limit, offset=offset, sort_by=sort_by, sort_dir=sort_dir, q=search)
        stmt = apply_sort(stmt, params, _DECISION_SORTABLE, default=MeetingDecision.due_date)
    else:
        stmt = stmt.order_by(
            MeetingDecision.due_date.is_(None), MeetingDecision.due_date, MeetingDecision.created_at
        )
    rows = (await db.execute(stmt.limit(limit).offset(offset))).all()
    result: list[DecisionTrackerRow] = []
    for decision, meeting, committee in rows:
        row = DecisionTrackerRow.model_validate(decision)
        row.committee_id = committee.id
        row.committee_reference = committee.reference
        row.committee_name = committee.name
        row.meeting_reference = meeting.reference
        row.meeting_title = meeting.title
        row.meeting_date = meeting.meeting_date
        result.append(row)
    return Page(items=result, total=total, limit=limit, offset=offset)


# ================================================================== summary ===
@router.get("/governance-summary", response_model=GovernanceSummary, dependencies=[_READ],
            summary="Board & committee governance roll-up for the dashboard")
async def governance_summary(db: DbSession) -> GovernanceSummary:
    committees = (await db.scalars(select(Committee).where(Committee.deleted.is_(False)))).all()
    committees_active = sum(1 for c in committees if c.status == CommitteeStatus.active)

    meetings = (await db.scalars(
        select(Meeting).join(Committee, Meeting.committee_id == Committee.id)
        .where(Committee.deleted.is_(False))
    )).all()
    meetings_held = sum(1 for m in meetings if m.status in (MeetingStatus.held, MeetingStatus.minuted))
    meetings_scheduled = sum(1 for m in meetings if m.status == MeetingStatus.scheduled)

    decisions = (await db.scalars(
        select(MeetingDecision)
        .join(Meeting, MeetingDecision.meeting_id == Meeting.id)
        .join(Committee, Meeting.committee_id == Committee.id)
        .where(Committee.deleted.is_(False))
    )).all()
    open_actions = sum(1 for d in decisions if d.status in (DecisionStatus.open, DecisionStatus.in_progress))
    overdue_actions = sum(1 for d in decisions if d.is_overdue)

    return GovernanceSummary(
        committees_total=len(committees),
        committees_active=committees_active,
        meetings_total=len(meetings),
        meetings_held=meetings_held,
        meetings_scheduled=meetings_scheduled,
        open_actions=open_actions,
        overdue_actions=overdue_actions,
    )



# ================================================================ board packs ===
async def _load_pack(db, pack_id: uuid.UUID) -> BoardPack:
    obj = await db.scalar(select(BoardPack).where(BoardPack.id == pack_id))
    if obj is None:
        raise HTTPException(status_code=404, detail="Board pack not found")
    return obj


async def _pack_reads(db, packs) -> list[BoardPackRead]:
    """Read models with committee, meeting, file and author names — one query each."""
    packs = list(packs)
    committee_ids = {p.committee_id for p in packs if p.committee_id}
    meeting_ids = {p.meeting_id for p in packs if p.meeting_id}
    file_ids = {f for p in packs for f in (p.pdf_file_id, p.xlsx_file_id) if f}
    committees = dict((await db.execute(
        select(Committee.id, Committee.name).where(Committee.id.in_(committee_ids))
    )).all()) if committee_ids else {}
    meetings = {m.id: m for m in (await db.execute(
        select(Meeting.id, Meeting.title, Meeting.meeting_date).where(Meeting.id.in_(meeting_ids))
    )).all()} if meeting_ids else {}
    files = {f.id: f for f in (await db.scalars(select(StoredFile).where(StoredFile.id.in_(file_ids)))).all()} if file_ids else {}
    people = await master_data.users_by_id(db, [p.generated_by_id for p in packs])

    def file_ref(fid):
        f = files.get(fid) if fid else None
        return BoardPackFile(id=f.id, filename=f.filename, content_type=f.content_type or "",
                             size_bytes=int(f.size_bytes or 0)) if f else None

    out = []
    for p in packs:
        who = people.get(p.generated_by_id) if p.generated_by_id else None
        meeting = meetings.get(p.meeting_id)
        out.append(BoardPackRead(
            id=p.id, committee_id=p.committee_id, committee_name=committees.get(p.committee_id, ""),
            meeting_id=p.meeting_id, meeting_title=meeting.title if meeting else "",
            meeting_date=meeting.meeting_date if meeting else None, title=p.title,
            period_start=p.period_start, period_end=p.period_end, sections=list(p.sections or []),
            status=p.status, error=p.error or "", pdf=file_ref(p.pdf_file_id), xlsx=file_ref(p.xlsx_file_id),
            generated_by_id=p.generated_by_id,
            generated_by=(who.full_name or who.email) if who else ("" if p.generated_by_id else board_pack.SCHEDULER_NAME),
            generated_at=p.generated_at, created_at=p.created_at,
        ))
    return out


@router.get("/board-packs/sections", response_model=list[BoardPackSection], dependencies=[_READ],
            summary="The sections a board pack can include, in pack order")
async def board_pack_sections() -> list[BoardPackSection]:
    return [BoardPackSection(key=k, title=t) for k, t in board_pack.SECTIONS]


@router.post("/board-packs", response_model=BoardPackRead, status_code=201, dependencies=[_WRITE],
             summary="Generate a board pack (PDF + XLSX) for a committee, a meeting or the organisation")
async def create_board_pack(body: BoardPackCreate, db: DbSession, user: CurrentUser) -> BoardPackRead:
    """Builds the pack now. The period defaults to the fiscal quarter to date; a period
    ending in the future, an unknown section or a meeting of another committee is a 422.
    A failure while building or rendering is kept on the returned pack (status
    ``failed`` with the reason) rather than lost."""
    committee = meeting = None
    if body.meeting_id is not None:
        meeting = await _load_meeting(db, body.meeting_id)
        if body.committee_id is not None and body.committee_id != meeting.committee_id:
            raise HTTPException(status_code=422, detail="meeting_id: that meeting belongs to another committee.")
        committee = await _load_committee(db, meeting.committee_id)
    elif body.committee_id is not None:
        committee = await _load_committee(db, body.committee_id)
    org = await board_pack.org_context(db, user.tenant_id)
    try:
        pack = await board_pack.generate(
            db, org, actor=user, committee=committee, meeting=meeting,
            period_start=body.period_start, period_end=body.period_end,
            sections=body.sections, title=body.title,
        )
    except board_pack.PackError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    return (await _pack_reads(db, [pack]))[0]


@router.get("/board-packs", response_model=Page[BoardPackRead], dependencies=[_READ],
            summary="Board packs, newest first")
async def list_board_packs(
    db: DbSession,
    committee_id: uuid.UUID | None = None,
    meeting_id: uuid.UUID | None = None,
    status_filter: Annotated[str | None, Query(alias="status", pattern="^(ready|failed)$")] = None,
    limit: Annotated[int, Query(ge=1, le=200)] = 50,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> Page[BoardPackRead]:
    stmt = select(BoardPack)
    if committee_id is not None:
        stmt = stmt.where(BoardPack.committee_id == committee_id)
    if meeting_id is not None:
        stmt = stmt.where(BoardPack.meeting_id == meeting_id)
    if status_filter is not None:
        stmt = stmt.where(BoardPack.status == status_filter)
    total = await db.scalar(select(func.count()).select_from(stmt.subquery())) or 0
    rows = (await db.scalars(
        stmt.order_by(BoardPack.generated_at.desc().nulls_last(), BoardPack.created_at.desc())
        .limit(limit).offset(offset)
    )).all()
    return Page(items=await _pack_reads(db, rows), total=total, limit=limit, offset=offset)


@router.get("/board-packs/{pack_id}", response_model=BoardPackRead, dependencies=[_READ])
async def get_board_pack(pack_id: uuid.UUID, db: DbSession) -> BoardPackRead:
    return (await _pack_reads(db, [await _load_pack(db, pack_id)]))[0]


async def _pack_download(db, user, pack_id: uuid.UUID, kind: str) -> FileResponse:
    pack = await _load_pack(db, pack_id)
    file_id = pack.pdf_file_id if kind == "pdf" else pack.xlsx_file_id
    sf = await db.get(StoredFile, file_id) if file_id else None
    if sf is None:
        reason = "it could not be generated" if pack.status == board_pack.FAILED else "the file was removed"
        raise HTTPException(status_code=404, detail=f"This board pack has no {kind.upper()} file: {reason}.")
    path = storage.resolve_path(user.tenant_id, sf.storage_key)
    return FileResponse(
        path, media_type=sf.content_type or "application/octet-stream", filename=sf.filename,
        headers={"Content-Disposition": f"attachment; filename*=UTF-8''{quote(sf.filename)}"},
    )


@router.get("/board-packs/{pack_id}/pdf", dependencies=[_READ], summary="Download the pack's PDF")
async def board_pack_pdf(pack_id: uuid.UUID, db: DbSession, user: CurrentUser) -> FileResponse:
    return await _pack_download(db, user, pack_id, "pdf")


@router.get("/board-packs/{pack_id}/xlsx", dependencies=[_READ], summary="Download the pack's spreadsheet")
async def board_pack_xlsx(pack_id: uuid.UUID, db: DbSession, user: CurrentUser) -> FileResponse:
    return await _pack_download(db, user, pack_id, "xlsx")
