"""Baseline schema — adopt Alembic from the create_all bootstrap.

This anchor migration materializes the entire ORM schema (every table registered on
``Base.metadata``) and applies the tenant-isolation Row-Level-Security policies. It
lets an existing ``create_all`` database (or a fresh one) come under Alembic control;
subsequent schema changes are added as normal autogenerated migrations that diff
against ``Base.metadata`` and are applied incrementally on top of this baseline.

Role provisioning and GRANTs for the least-privilege runtime role remain a deploy
step (``python -m app.db.init_db`` or a managed grant), not schema, so they are not
emitted here.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-03
"""
from __future__ import annotations

from alembic import op

# Importing the models package registers every table on Base.metadata.
import app.models  # noqa: F401
from app.core.database import Base
from app.db.rls import rls_ddl_statements

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    # Create every table from the live ORM metadata (idempotent via checkfirst).
    Base.metadata.create_all(bind=bind, checkfirst=True)
    # Enforce tenant isolation on every tenant-scoped table.
    for statement in rls_ddl_statements():
        op.execute(statement)


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
