"""Permission catalog and default role definitions.

Permissions follow a ``resource:action`` convention. Add new resources here as new
modules land; the seeder reconciles the catalog and default roles on startup.
"""
from __future__ import annotations

# --- Catalog: code -> human description ---
PERMISSION_CATALOG: dict[str, str] = {
    "risk:read": "View risks",
    "risk:write": "Create and edit risks",
    "risk:delete": "Delete risks",
    "risk:accept": "Approve risk acceptances",
    "control:read": "View controls",
    "control:write": "Create and edit controls",
    "compliance:read": "View frameworks and requirements",
    "compliance:write": "Manage frameworks, requirements and control mappings",
    "incident:read": "View incidents",
    "incident:write": "Create and manage incidents",
    "policy:read": "View policies",
    "policy:write": "Create and manage policies",
    "vendor:read": "View third parties / vendors",
    "vendor:write": "Manage third parties / vendors",
    "assessment:read": "View questionnaires and vendor assessments",
    "assessment:write": "Build questionnaires and run vendor assessments",
    "org:read": "View business units, processes and legal register",
    "org:write": "Manage business units, processes and legal register",
    "exception:read": "View exceptions",
    "exception:write": "Create and manage exceptions",
    "exception:approve": "Approve or reject exceptions",
    "project:read": "View projects",
    "project:write": "Create and manage projects and tasks",
    "goal:read": "View strategic goals",
    "goal:write": "Manage goals and record goal audits",
    "bcp:read": "View business continuity plans",
    "bcp:write": "Manage continuity plans, tasks and tests",
    "privacy:read": "View records of processing (RoPA)",
    "privacy:write": "Manage records of processing (RoPA / GDPR)",
    "review:read": "View access reviews / certifications",
    "review:write": "Run access reviews and certify accounts",
    "awareness:read": "View awareness training programs",
    "awareness:write": "Manage awareness programs and training",
    "workflow:read": "View approval requests",
    "workflow:write": "Submit and cancel approval requests",
    "workflow:approve": "Approve or reject approval requests",
    "customfield:manage": "Define and manage custom fields",
    "report:read": "View KPI dashboards and reports",
    "report:write": "Build and manage dashboard widgets",
    "integration:manage": "Manage webhooks and integrations",
    "automation:manage": "Define dynamic status rules",
    "sso:manage": "Configure single sign-on (SSO)",
    "asset:read": "View assets",
    "asset:write": "Create and edit assets",
    "user:read": "View users",
    "user:write": "Manage users",
    "role:read": "View roles",
    "role:write": "Manage roles",
    "audit:read": "View the activity log",
    "internal_audit:read": "View the audit universe, engagements and findings",
    "internal_audit:write": "Manage internal-audit engagements, working papers and findings",
    "shariah:read": "View Shariah rulings, Islamic products, reviews and the charity ledger",
    "shariah:write": "Manage Shariah governance: rulings, products, reviews, SNC findings, purification",
    "oprisk:read": "View RCSA, KRIs and the operational loss database",
    "oprisk:write": "Manage RCSA assessments, KRIs and operational loss events",
    "aml:read": "View AML/CFT screening, STR/SAR filings and AML risk assessments",
    "aml:write": "Manage AML/CFT screening, STR/SAR filings and AML risk assessments",
}

ALL_PERMISSIONS = list(PERMISSION_CATALOG.keys())

# Read-only subset, used by the Viewer role.
_READ_ONLY = [p for p in ALL_PERMISSIONS if p.endswith(":read")]

# --- Default roles seeded per tenant: name -> (description, permission codes) ---
DEFAULT_ROLES: dict[str, tuple[str, list[str]]] = {
    "Admin": ("Full administrative access", ALL_PERMISSIONS),
    "Risk Manager": (
        "Manage risks, controls, assets, incidents and vendors",
        [
            "risk:read",
            "risk:write",
            "risk:delete",
            "control:read",
            "control:write",
            "asset:read",
            "asset:write",
            "incident:read",
            "incident:write",
            "vendor:read",
            "vendor:write",
            "assessment:read",
            "assessment:write",
            "org:read",
            "org:write",
            "exception:read",
            "exception:write",
            "project:read",
            "project:write",
            "goal:read",
            "goal:write",
            "bcp:read",
            "bcp:write",
            "review:read",
            "review:write",
            "workflow:read",
            "workflow:write",
            "report:read",
            "report:write",
            "audit:read",
            "oprisk:read",
            "oprisk:write",
        ],
    ),
    "Risk Approver": (
        "Review and approve risk acceptances, exceptions and approval requests",
        [
            "risk:read",
            "risk:accept",
            "control:read",
            "asset:read",
            "exception:read",
            "exception:approve",
            "workflow:read",
            "workflow:approve",
            "audit:read",
        ],
    ),
    "Compliance Manager": (
        "Manage compliance frameworks, control mappings and policies",
        [
            "compliance:read",
            "compliance:write",
            "control:read",
            "control:write",
            "policy:read",
            "policy:write",
            "privacy:read",
            "privacy:write",
            "awareness:read",
            "awareness:write",
            "workflow:read",
            "workflow:write",
            "report:read",
            "report:write",
            "risk:read",
            "exception:read",
            "exception:write",
            "audit:read",
            "internal_audit:read",
            "shariah:read",
            "shariah:write",
            "aml:read",
            "aml:write",
        ],
    ),
    "Auditor": (
        "Assurance role: read-only across the platform, plus full internal-audit management",
        _READ_ONLY + ["internal_audit:write"],
    ),
    "Viewer": ("Read-only access", _READ_ONLY),
}
